# Docker Compose Production Environments 
version : '3'
services:
        aiohttp:
                env_file: .env
                build:
                        context: .
                image: bni-fake-server
                entrypoint: make run-gunicorn
                restart: unless-stopped
                ports:
                - 8066:7000
                logging:
                  driver: "json-file"
                  options:
                    max-size: "100k"
                    max-file: "10"
